const img = "/images/tara/";

module.exports = [
  { id: "wrap-dress-lumiere", name: "Wickelkleid Lumière", price: 98, category: "Kleider", badge: "Neu", colors: ["creme", "rose", "sage"], image: `${img}product-wrap-dress-01.webp`, hoverImage: `${img}product-wrap-dress-02.webp`, alt: "Wickelkleid Lumière aus cremefarbener Bio-Baumwolle", hoverAlt: "Wickelkleid Lumière getragen im warmen Tageslicht" },
  { id: "blouse-aurore", name: "Oversized Bluse Aurore", price: 68, category: "Blusen & Tops", colors: ["creme", "lavender"], image: `${img}product-blouse-01.webp`, hoverImage: `${img}product-blouse-02.webp`, alt: "Oversized Bluse Aurore aus weicher Bio-Baumwolle", hoverAlt: "Oversized Bluse Aurore kombiniert mit weiter Baumwollhose" },
  { id: "trouser-soleil", name: "Weite Hose Soleil", price: 85, category: "Hosen", colors: ["sand", "espresso"], image: `${img}product-trouser-01.webp`, hoverImage: `${img}product-trouser-02.webp`, alt: "Weite Hose Soleil aus Baumwolle in Sand", hoverAlt: "Weite Hose Soleil in einer entspannten Capsule-Kombination" },
  { id: "tee-douceur", name: "Essential Tee Douceur", price: 38, category: "T-Shirts", badge: "Bestseller", colors: ["rose", "creme", "espresso", "sage"], image: `${img}product-tee-01.webp`, hoverImage: `${img}product-tee-02.webp`, alt: "Essential Tee Douceur aus Bio-Baumwolle", hoverAlt: "Essential Tee Douceur unter Baumwoll-Cardigan gestylt" },
  { id: "cardigan-tendresse", name: "Strick-Cardigan Tendresse", price: 78, category: "Strickwaren", colors: ["lavender", "creme"], image: `${img}product-cardigan-01.webp`, hoverImage: `${img}product-cardigan-02.webp`, alt: "Strick-Cardigan Tendresse aus Baumwolle", hoverAlt: "Strick-Cardigan Tendresse über einer hellen Bluse" },
  { id: "midi-skirt-jardin", name: "Midi-Rock Jardin", price: 72, category: "Röcke", colors: ["sage", "terracotta"], image: `${img}product-skirt-01.webp`, hoverImage: `${img}product-skirt-02.webp`, alt: "Midi-Rock Jardin aus Baumwolle in Salbei", hoverAlt: "Midi-Rock Jardin mit Baumwolltop kombiniert" },
  { id: "blazer-clarte", name: "Baumwoll-Blazer Clarté", price: 118, category: "Jacken", badge: "Neu", colors: ["sand", "creme"], image: `${img}product-blazer-01.webp`, hoverImage: `${img}product-blazer-02.webp`, alt: "Baumwoll-Blazer Clarté in warmem Sandton", hoverAlt: "Baumwoll-Blazer Clarté als leichte Sommerjacke" },
  { id: "top-matin", name: "Baumwoll-Top Matin", price: 42, category: "Blusen & Tops", colors: ["rose", "lavender", "creme"], image: `${img}product-top-01.webp`, hoverImage: `${img}product-top-02.webp`, alt: "Baumwoll-Top Matin in zartem Rose", hoverAlt: "Baumwoll-Top Matin mit weiter Hose" },
  { id: "maxi-dress-etoile", name: "Maxikleid Étoile", price: 112, category: "Kleider", colors: ["terracotta", "creme"], image: `${img}product-maxi-dress-01.webp`, hoverImage: `${img}product-maxi-dress-02.webp`, alt: "Maxikleid Étoile aus fließender Baumwolle", hoverAlt: "Maxikleid Étoile in natürlichem Abendlicht" },
  { id: "culotte-brise", name: "Culotte Brise", price: 76, category: "Hosen", colors: ["creme", "espresso"], image: `${img}product-culotte-01.webp`, hoverImage: `${img}product-culotte-02.webp`, alt: "Culotte Brise aus Baumwolle in Creme", hoverAlt: "Culotte Brise mit Oversized Bluse kombiniert" },
  { id: "shirt-horizon", name: "Leinenhemd Horizon", price: 62, category: "Blusen & Tops", badge: "Neu", colors: ["creme", "accent"], image: `${img}product-shirt-01.webp`, hoverImage: `${img}product-shirt-02.webp`, alt: "Leinenhemd Horizon aus Baumwoll-Leinen-Mix", hoverAlt: "Leinenhemd Horizon offen über Baumwolltop getragen" },
  { id: "jersey-dress-murmure", name: "Jersey-Kleid Murmure", price: 88, category: "Kleider", colors: ["lavender", "rose"], image: `${img}product-jersey-dress-01.webp`, hoverImage: `${img}product-jersey-dress-02.webp`, alt: "Jersey-Kleid Murmure aus weicher Baumwolle", hoverAlt: "Jersey-Kleid Murmure in entspannter Alltagsszene" },
  { id: "shorts-riviere", name: "Shorts Riviere", price: 48, category: "Hosen", colors: ["sand", "sage"], image: `${img}product-shorts-01.webp`, hoverImage: `${img}product-shorts-02.webp`, alt: "Shorts Riviere aus robuster Baumwolle", hoverAlt: "Shorts Riviere mit Bluse und Sandalen" },
  { id: "wrap-top-caresse", name: "Wickeltop Caresse", price: 45, category: "Blusen & Tops", badge: "Bestseller", colors: ["accent", "creme", "lavender"], image: `${img}product-wrap-top-01.webp`, hoverImage: `${img}product-wrap-top-02.webp`, alt: "Wickeltop Caresse aus Bio-Baumwolle", hoverAlt: "Wickeltop Caresse mit A-Linien-Rock" },
  { id: "a-line-skirt-petale", name: "A-Linien-Rock Petale", price: 68, category: "Röcke", colors: ["terracotta", "sand"], image: `${img}product-a-line-skirt-01.webp`, hoverImage: `${img}product-a-line-skirt-02.webp`, alt: "A-Linien-Rock Petale aus Baumwolle", hoverAlt: "A-Linien-Rock Petale mit weichem Baumwollshirt" },
  { id: "pullover-nuage", name: "Strickpullover Nuage", price: 72, category: "Strickwaren", colors: ["rose", "sage"], image: `${img}product-pullover-01.webp`, hoverImage: `${img}product-pullover-02.webp`, alt: "Strickpullover Nuage aus Baumwollgarn", hoverAlt: "Strickpullover Nuage locker über der Schulter getragen" },
  { id: "shirt-dress-aube", name: "Hemdblusenkleid Aube", price: 105, category: "Kleider", badge: "Neu", colors: ["creme", "accent"], image: `${img}product-shirt-dress-01.webp`, hoverImage: `${img}product-shirt-dress-02.webp`, alt: "Hemdblusenkleid Aube aus heller Baumwolle", hoverAlt: "Hemdblusenkleid Aube mit Bindegurt getragen" },
  { id: "palazzo-velours", name: "Palazzo-Hose Velours", price: 82, category: "Hosen", colors: ["espresso", "sand", "terracotta"], image: `${img}product-palazzo-01.webp`, hoverImage: `${img}product-palazzo-02.webp`, alt: "Palazzo-Hose Velours aus schwerer Baumwolle", hoverAlt: "Palazzo-Hose Velours mit Wickeltop kombiniert" }
];
